#!/bin/bash
exec >ovs-stop-stderrout.txt
exec 2>&1

echo "args: $@"
echo
echo "hostname: `hostname`"
echo
pidfile="ovs-collect-pid.txt"

if [ -e $pidfile ]; then
    pid=`cat $pidfile`
    if [ -z "$pid" ]; then
        echo "PID for ovs-collect ($pidfile) not found"
        exit 1
    fi
    if [ -e /proc/$pid ]; then
        kill -s SIGTERM $pid
    else
        echo "ERROR: process ID $pid was not found, so ovs-collect may have terminated abnormally"
    fi
else
    echo "$pidfile not found"
    echo "PWD: `/bin/pwd`"
    echo "LS:"
    /bin/ls -l
    exit 1
fi
if [ -f /usr/bin/xz ]; then
    echo "Compressing any ovs data files"
    xz -T 0 ofctl*.txt
    xz -T 0 dpctl*.txt
    xz -T 0 conntrack*.txt
fi
